### ISSUE TITLE
Add CI tests that run the installer

### ISSUE THREAD

**Issue by rrnewton** [cloudseal/cloudseal.github.io#1]
Azure CI is activated [for this repo here](https://dev.azure.com/cloudseal/cloudseal-public/_build?definitionId=7&_a=summary).  The only thing in this repo right now is the "getit" installer script. 

A simple test would be to install with the script, and then run `cloudseal ls -l` to confirm that it seems to work.  This could be done in various modes:

 * [x] run as non-root in the CI VM, installing to one or more local locations (ideally a relative location with spaces!)
 * install as root inside a Docker image, testing standard base images
    - [x] Ubuntu
    - [x] Fedora
    - [ ] Nix

(And however many other distros we feel like testing...)

We should install but not run on a Mac (and windows) agent just to make sure the bash script installer and its use of system dependencies (utilities like `readlink`, `install`) are broadly portable.

**Comment by jasonwhite** [comment]
Fixed in #2. Testing on Nix will be a little different from the rest. It's probably better to write a nix expression for that instead of using the install script.

**Comment by rrnewton** [comment]
Yeah, it would be handy to have a nix expression.  

However the plan for Docker integration with the forthcoming cloudseal CLI (CC @loganwendholt) does make it necessary for our install packages to work even when bind-mounted into some arbitrary Linux containers. For example, if someone replaces `docker run nixos/nix ...` with `cs run nixos/nix ...`, then we never properly interact with Nix, we just get mapped into the file system.

If we're doing things right, testing with different distros should be mostly superfluous, as we shouldn't be relying on any aspect of the file system at all (e.g. the current `/lib` dependence is a bug).  Probably a more important test is to try to run on some kind of empty file system to flush out problems like that.
